version: '3'
services:
  app:
    build: .
    # Node.jsのグローバル変数です。開発用途なのでdevelopmentを指定
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    working_dir: /app
    # command: 
    # ports:
    #   - 8000:3000
    tty: true
    network_mode: host